-- One-time seed for the demo dataset - generated by worker/generate-seed-sql.mjs.
-- Fictitious data only. Paste into the D1 console AFTER running all 9 schema migrations.

INSERT INTO payment_policies (project_id, reviewed, milestones_json, hour_bank_size) VALUES ('9100000003', 1, '[{"id":"m1","note":"תחילת עבודה","percent":25,"trigger":"start","customDate":null,"monthsAfterStart":null,"timeConfirmed":true},{"id":"m2","note":"אישור עיצוב","percent":30,"trigger":"custom","customDate":"2026-04-19","monthsAfterStart":null,"timeConfirmed":true},{"id":"m3","note":"מסירה סופית","percent":45,"trigger":"end","customDate":null,"monthsAfterStart":5,"timeConfirmed":false}]', NULL);
INSERT INTO payment_policies (project_id, reviewed, milestones_json, hour_bank_size) VALUES ('9100000004', 1, '[{"id":"m1","note":"מסירת מערכת","percent":100,"trigger":"end","customDate":null,"monthsAfterStart":null,"timeConfirmed":true}]', 140);
INSERT INTO payment_policies (project_id, reviewed, milestones_json, hour_bank_size) VALUES ('9100000006', 1, '[{"id":"m1","note":"תחילת פיתוח","percent":40,"trigger":"start","customDate":null,"monthsAfterStart":null,"timeConfirmed":true},{"id":"m2","note":"השקה","percent":60,"trigger":"end","customDate":null,"monthsAfterStart":null,"timeConfirmed":true}]', NULL);

INSERT INTO schedule_change_events (project_id, changed_at, new_end_date) VALUES ('9100000003', '2026-07-10T08:57:58.351Z', '2026-08-19');
INSERT INTO schedule_change_events (project_id, changed_at, new_end_date) VALUES ('9100000006', '2026-06-29T08:57:58.351Z', '2026-09-19');

INSERT INTO task_status_history (task_id, done_at) VALUES ('9000000039', '2026-07-05T08:57:58.351Z');
